{% set version = "1.2.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml2
  version: {{ version|replace("-", "_") }}

source:
  fn: xml2_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/xml2_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/xml2/xml2_{{ version }}.tar.gz
  sha256: 0a7a916fe9c5da9ac45aeb4c6b6b25d33c07652d422b9f2bb570f2e8f4ac9494

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-bh
    - r-rcpp >=0.11.4.6
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-bh
    - r-rcpp >=0.11.4.6

test:
  commands:
    - $R -e "library('xml2')"  # [not win]
    - "\"%R%\" -e \"library('xml2')\""  # [win]

about:
  home: https://github.com/hadley/xml2/
  license: GPL (>= 2)
  summary: Work with XML files using a simple, consistent interface. Built on top of the 'libxml2'
    C library.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
