# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lvR4KtyQBxSvwuKEUD6UTorfLTCg0jWt0dfQbnv/PVH97ZViZuQrA1imZYXM6Np506MdvZbxARqJOgEKfEw7rU4EtqoVdilreGj2ZwMrVRuHX1NGNjcbzRMYN98NuEpz44tftUN41yUdQS8/RruO71r3LQo+hQDGMM34BF91bGI/toT9Hz6postgabmDDHo3/CLVB7U7zsdg2HcbRhKqKsr6/PU5QOdxk2jjyJbPcb2cHzqIV4vXCuE3qwsbkjtLUob9i4h4pEUApfqUa+TewT120kl/poifxP6U6tqbBY4xidd2adh0X04hTqooDyMq9wScVa+785FmEXjKl+oUT+fE+1XaptlzYvLCsv6iucNM8TgI1mX/6dOey/TkJF+VC8xjrH4/3mn1Qg+iHs7/uqcCiSm0yObQQu7KTpEoI1ducNUh5Muix5gYu/bb/a90vxSb7rj1/8Qrj7TVDUzUR7WJuU6G1tnozvWiikC9OLz4souQm0qNlEPkT5byvdyGCsEAcM/CmlqOunrBc1OLAeZzpQ+Ovl1ujq42LlOfJOoFlO5R6lJa6s6kENuHdYTrP7cSK99Hq832GavXbSKUBAUNF3Ai8AX9WwYB6wmaVph40bd6Zqm+sxK0esThpb2PFhAgXdjeaug74lIQoIe7Xrygwp75Phwdm8Vx9Kqc/9s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
